# Lezione 1: Introduzione alla Vettorizzazione in Python

Le operazioni vettoriali in NumPy permettono di sfruttare funzioni matematiche precompilate e ottimizzate, pensate per lavorare in modo efficiente su interi array o sequenze di dati. In particolare, NumPy mette a disposizione un ampio insieme di funzioni di algebra lineare, utili per eseguire calcoli complessi come prodotti scalari, moltiplicazioni tra matrici, calcolo di determinanti, autovalori, e molto altro.

NumPy - funzioni algebra lineare - documentazione ufficiale:
https://numpy.org/doc/stable/reference/routines.linalg.html

La vettorizzazione consiste nell’eseguire operazioni su più elementi di un array senza utilizzare cicli for espliciti, riducendo così il tempo di esecuzione e il carico computazionale.

Le operazioni vettoriali con NumPy risultano molto più veloci ed efficienti rispetto alle soluzioni basate su cicli tradizionali, specialmente quando si lavora su grandi volumi di dati.

In altre parole, la vettorizzazione trasforma un’operazione che normalmente agirebbe su un singolo elemento per volta, in un’operazione in cui una singola istruzione agisce contemporaneamente su più elementi (concetto noto come SIMD - Single Instruction, Multiple Data).

## Operazioni tra vettori

Iniziamo con alcuni semplici esempi di operazioni su vettori e matrici. Importiamo la libreria numpy e la libreria time per paragonare i tempi di esecuzione.


In [1]:
import numpy as np
import time


Proviamo a sommare tutti gli elemento di un vettore (o array) prima con un loop e poi usando la funzione **sum** della libreria Numpy. https://numpy.org/doc/stable/reference/generated/numpy.sum.html

In [36]:
start_time = time.time()
total = 0
array = np.arange(30000)
for i in range(len(array)):
    total += array[i] # sommo i-esimo elemento
end_time = time.time()
print(f"Somma (ciclo for): {total}")
print(f"Tempo di esecuzione (ciclo for): {1000 * (end_time - start_time):.4f} ms")

start_time = time.time()
total_numpy = np.sum(np.arange(30000))
end_time = time.time()
print(f"Somma (NumPy): {total_numpy}")
print(f"Tempo di esecuzione (NumPy): {1000 * (end_time - start_time):.4f} ms")

Somma (ciclo for): 449985000
Tempo di esecuzione (ciclo for): 4.3252 ms
Somma (NumPy): 449985000
Tempo di esecuzione (NumPy): 2.1949 ms


Dato un vettore a e un vettore b della stessa lunghezza, il prodotto scalare è un’operazione che restituisce un singolo numero (uno scalare).

Si calcola moltiplicando ogni elemento del primo vettore per l’elemento corrispondente del secondo vettore (cioè l’elemento nella stessa posizione) e sommando tutti i risultati.

I due vettori devono avere lo stesso numero di elementi.

Se
a = [a₁, a₂, a₃, …, aₙ]
e
b = [b₁, b₂, b₃, …, bₙ]

Allora:
Prodotto scalare = a₁ * b₁ + a₂ * b₂ + a₃ * b₃ + … + aₙ * bₙ

In [9]:
# Creazione di due array NumPy

# Array 'a': contiene i numeri da 0 a 49999 (50.000 elementi)
a = np.arange(50000)
print(f"Esempio: a[100] = {a[100]}")  # Visualizza il valore all'indice 100

# Array 'b': contiene i numeri da 50000 a 99999 (altri 50.000 elementi)
b = np.arange(50000, 100000)
print(f"Esempio: b[100] = {b[100]}")  # Visualizza il valore all'indice 100

# ----------------------------------------------
# Prodotto scalare usando un ciclo for (modo classico non vettoriale)
# ----------------------------------------------
start_time = time.process_time()

dot_product_loop = 0
for i in range(len(a)):
    dot_product_loop += a[i] * b[i]

end_time = time.process_time()
print(f"\nProdotto scalare con ciclo for: {dot_product_loop}")
print(f"Tempo di esecuzione (ciclo for): {1000 * (end_time - start_time):.4f} ms")
print(f"Risultato dot product: : {dot_product_loop}")

# adesso usiamo la funzione dot della libreria Numpy https://numpy.org/doc/stable/reference/generated/numpy.dot.html
# che permette di calcolare il prodotto
start_time = time.process_time()
dot_product_numpy = np.dot(a, b)
end_time = time.process_time()
print(f"Prodotto scalare (NumPy): {dot_product_numpy}")
print(f"Tempo di esecuzione (NumPy): {1000 * (end_time - start_time):.4f} ms")
print(f"Risultato dot product numpy: : {dot_product_loop}")

Esempio: a[100] = 100
Esempio: b[100] = 50100

Prodotto scalare con ciclo for: 104164166675000
Tempo di esecuzione (ciclo for): 11.6040 ms
Risultato dot product: : 104164166675000
Prodotto scalare (NumPy): 104164166675000
Tempo di esecuzione (NumPy): 0.8800 ms
Risultato dot product: : 104164166675000


## Operazioni tra matrici

In Numpy una matrice è un array multidimensionale (ndarray), ovvero un 2D array o un array bidimensionale. Ogni riga della matrice viene vista come una lista di elementi. Una matrice è quindi una lista di liste. NumPy memorizza tutto in un unico blocco di memoria contiguo, ottimizzato per l’accesso veloce. Dichiariamo una matrice A di dimensione 2X3, 2 righe e 3 colonne.

In [18]:
matrice_a = np.array([[1, 2, 3],
                    [4, 5, 6]])
print(matrice_a)
print(f"La matrice ha dimensione {matrice_a.shape}")
print(f"Esempio elemento prima riga seconda colonna : {matrice_a[0][1]}")
print(f"Esempio elemento seconda riga seconda colonna : {matrice_a[1][1]}")

[[1 2 3]
 [4 5 6]]
La matrice ha dimensione (2, 3)
Esempio elemento prima riga seconda colonna : 2
Esempio elemento seconda riga seconda colonna : 5


Vediamo due tipi di moltiplicazione tra matrici fondamentali anche per comprendere meglio il deep learning: la moltiplicazione elemento per elemento (detta element wise) la moltiplirazione tra matrici detta prodotto.

### Moltiplicazione elemento per elemento (element-wise)

In questa modalità, ogni elemento della prima matrice viene moltiplicato per l’elemento corrispondente della seconda matrice, cioè con lo stesso indice di riga e colonna.

**Requisito:**
Le due matrici devono avere esattamente la stessa dimensione.

In NumPy si fa con:
- `np.multiply(A, B)`
oppure
- `A * B`

Vediamo un piccolo esempio.

In [22]:
# dichiariamo un'altra matrice b
matrice_b = np.array([[1, 2, 1],
                    [2, 2, 2]])
elementwise_product = np.multiply(matrice_a, matrice_b)
elementwise_product = matrice_a * matrice_b
print(elementwise_product)

[[ 1  4  3]
 [ 8 10 12]]


Ora vediamo esempio su matrici grandi con loop e con numpy.

In [27]:
# Creiamo la prima matrice con valori da 0 a 49999
# La forma finale sarà (250, 200) → 250 righe x 200 colonne = 50.000 elementi
matrice_a = np.arange(50000).reshape((250, 200))

# Creiamo la seconda matrice con valori da 50000 a 99999
# Stessa forma: (250, 200)
matrice_b = np.arange(50000, 100000).reshape((250, 200))

elementwise_product_loop = np.zeros_like(matrice_a)
# Eseguiamo la moltiplicazione elemento per elemento con due for annidati
start_time = time.time()
for i in range(matrice_a.shape[0]):        # Scorre le righe
    for j in range(matrice_a.shape[1]):    # Scorre le colonne
        elementwise_product_loop[i, j] = matrice_a[i, j] * matrice_b[i, j]
end_time = time.time()
print(f"Tempo di esecuzione (ciclo for): {1000 * (end_time - start_time):.4f} ms")

start_time = time.time()
elementwise_product = matrice_a * matrice_b
end_time = time.time()
print(f"Tempo di esecuzione (numpy): {1000 * (end_time - start_time):.4f} ms")

print("Risultato moltiplicazione element-wise con loop:")
print(elementwise_product_loop)

Tempo di esecuzione (ciclo for): 15.8241 ms
Tempo di esecuzione (numpy): 0.4690 ms
Risultato moltiplicazione element-wise con loop:
[[         0      50001     100004 ...    9888809    9939204    9989601]
 [  10040000   10090401   10140804 ...   20007609   20058404   20109201]
 [  20160000   20210801   20261604 ...   30206409   30257604   30308801]
 ...
 [4910360000 4910508801 4910657604 ... 4939712409 4939861604 4940010801]
 [4940160000 4940309201 4940458404 ... 4969591209 4969740804 4969890401]
 [4970040000 4970189601 4970339204 ... 4999550009 4999700004 4999850001]]


 ### Moltiplicazione tra matrici (matricial multiplication o prodotto tra matrici)
Data una matrice reale **A** di dimensione **m × n** (con **m righe** e **n colonne**) e una matrice reale **B** di dimensione **n × p** (con **n righe** e **p colonne**), il loro **prodotto matriciale** è una nuova matrice reale **C** di dimensione **m × p**. Ogni elemento **cᵢₖ** della matrice **C** si ottiene calcolando la **somma dei prodotti tragli elementi della riga `i` di A e della colonna `k` di B**. In altre parole:
- Si prende la **riga `i` della matrice A**
- Si prende la **colonna `k` della matrice B**
- Si moltiplicano gli elementi corrispondenti (element-wise sulla riga e sulla colonna)
- Si sommano i prodotti → il risultato diventa **cᵢₖ**, elemento della matrice **C**

![Testo alternativo](img/00_esempioProdottoMatrici.gif)

**Requisito:**
Il numero di colonne della prima matrice deve essere uguale al numero di righe della seconda matrice.

In NumPy si fa con:
- `np.dot(A, B)`
oppure
- `A @ B`

| Tipo di moltiplicazione        | Requisito dimensionale                | Sintassi NumPy                    |
|--------------------------------|--------------------------------------|-----------------------------------|
| Element-wise                   | Matrici della stessa dimensione      | `A * B` oppure `np.multiply(A, B)`|
| Matriciale                     | Colonne di A = Righe di B            | `np.dot(A, B)` oppure `A @ B`    |


Ora vediamo esempio su matrici grandi con loop e con numpy.

In [35]:
# per moltiplicare la mtrice A con la matrice B dobbiamo fare il reshape della matrice A perché il numero di colonne di A deve essere lo stesso del numero di righe di B

matrice_a_reshaped = matrice_a.reshape((200, 250))
print(f"Nuova forma della matrice A: {matrice_a_reshaped.shape}")
print(matrice_a_reshaped[0][249])
print(f"Forma matrice B: {matrice_b.shape}")

# Prodotto matriciale con ciclo
# Creiamo una matrice risultato con forma (200, 100)
result_loop = np.zeros((matrice_a_reshaped.shape[0], matrice_b.shape[1]))

start_time = time.time()
for i in range(matrice_a_reshaped.shape[0]):  # Righe di A
    for j in range(matrice_b.shape[1]):  # Colonne di B
        somma = 0
        for k in range(matrice_a_reshaped.shape[1]):  # Colonne di A / Righe di B
            somma += matrice_a_reshaped[i, k] * matrice_b[k, j]
        result_loop[i, j] = somma
end_time = time.time()
print(f"Tempo di esecuzione (ciclo for - prodotto matriciale): {1000 * (end_time - start_time):.4f} ms")

# Prodotto matriciale con NumPy (modo vettoriale e ottimizzato)
start_time = time.time()
result_numpy = np.dot(matrice_a_reshaped, matrice_b)
# In alternativa:
# result_numpy = matrice_a @ matrice_b
end_time = time.time()
print(f"Tempo di esecuzione (NumPy dot): {1000 * (end_time - start_time):.4f} ms")

Nuova forma della matrice A: (200, 250)
249
Forma matrice B: (250, 200)
Tempo di esecuzione (ciclo for - prodotto matriciale): 2450.0768 ms
Tempo di esecuzione (NumPy dot): 4.0262 ms
